Repository ubsuny/23-Homework6G3, pull requests merged in 2023-11, with the labels that each got.

#11 Add Apache 2.0 license.
  LICENSE
Labels: helpful, license

#12 Initialize github actions and create library named calculus.py with necessary functios.
  .github/workflows/demo.yml
  .github/workflows/greetings.yml
  .github/workflows/unittesting_pytest.yml
  calculus.py
Labels: important

#14 Documentation.
  documentation.md
Labels: documentation

#19 Add Missing docstring in the [calculus.py](https://github.com/ubsuny/23-Homework6G3/blob/929ba470c2f70b9afdc6576c0e25fc851a6a9ffc/calculus.py)
  calculus.py
Labels: task 3

#24 Task 3
  calculus.py
Labels: milestones, update, task 3

#48 Create git hub action flow for linting test_calculus.py.
  .github/workflows/lint_test_calculus.yml
  test_calculus.py
Labels: update, task 3

#58 Task 3
  images/pylint1.png
  images/pylint2.png
  images/pylint3.png
  images/pytest_hw6G3_test_calculus.png
  task3_docs.md
Labels: documentation

#66 Task 3 final
  .github/workflows/lint_calculus.yml
  calculus.py
  images/pylint1_calculus.png
  images/pylint_calculus.png
  task3_docs.md
Labels: update, task 3

#57 Docstring and comments added
  calculus_main.py
Labels: update, task 2

#71 final merge request
  demo_rootfinding.ipynb
  main_rootfinding.py
  rootfinding.py
Labels: urgent
